-- T-21: 홈페이지 반영 웹훅 상태를 기록하는 단일 행 테이블(ADR-010).
CREATE TABLE homepage_sync_status (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    last_succeeded_at TIMESTAMPTZ,
    last_failed_at    TIMESTAMPTZ,
    pending_tags      TEXT
);

INSERT INTO homepage_sync_status (id) VALUES (1);
