-- 게임 정보 스키마 (05-api-spec.md §1.3, T-36). track_page와 동일하게 game만 최상위(soft delete)고
-- 하위(screenshot/rating/build/member)는 ON DELETE CASCADE로 물리 삭제한다.
-- 게임 빌드는 이번 1차에서 메타데이터만 다룬다 — build_file_url은 실제 업로드 파이프라인(T-41,
-- ADR-023)이 붙기 전까지 항상 NULL이다.

CREATE TABLE game (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug           VARCHAR(50)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    one_liner      VARCHAR(500) NOT NULL,
    track_id       BIGINT       REFERENCES track (id),
    team_label     VARCHAR(30),
    description    TEXT,
    thumbnail_url  VARCHAR(500),
    display_order  INT          NOT NULL,
    is_published   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_game_slug ON game (slug) WHERE deleted_at IS NULL;

CREATE TABLE game_screenshot (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id        BIGINT       NOT NULL REFERENCES game (id) ON DELETE CASCADE,
    image_url      VARCHAR(500) NOT NULL,
    display_order  INT          NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_game_screenshot ON game_screenshot (game_id, display_order);

-- 선택 입력: 행이 없으면 공개 응답의 rating이 null (AC-9.8)
CREATE TABLE game_rating (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id                  BIGINT      NOT NULL REFERENCES game (id) ON DELETE CASCADE,
    rating                   VARCHAR(10) NOT NULL,
    classification_number    VARCHAR(100),
    classification_date      DATE,
    business_name            VARCHAR(200),
    developer_report_number  VARCHAR(100),
    desc_sexuality           BOOLEAN     NOT NULL DEFAULT FALSE,
    desc_violence            BOOLEAN     NOT NULL DEFAULT FALSE,
    desc_fear                BOOLEAN     NOT NULL DEFAULT FALSE,
    desc_language            BOOLEAN     NOT NULL DEFAULT FALSE,
    desc_drugs               BOOLEAN     NOT NULL DEFAULT FALSE,
    desc_crime               BOOLEAN     NOT NULL DEFAULT FALSE,
    desc_gambling            BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (game_id)
);

-- 1차: 메타데이터만. build_file_url·canvas 크기는 실제 업로드 파이프라인이 붙기 전까지 비어 있을 수 있다 (ADR-023 §범위)
CREATE TABLE game_build (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id         BIGINT      NOT NULL REFERENCES game (id) ON DELETE CASCADE,
    version         VARCHAR(30) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    canvas_width    INT,
    canvas_height   INT,
    storage_bytes   BIGINT,
    build_file_url  VARCHAR(500),
    uploaded_by     BIGINT      REFERENCES member (id),
    uploaded_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_game_build_active ON game_build (game_id, status);

-- 명부가 이미 구현되어 있으므로 FK를 즉시 적용한다 (ADR-012 패턴 재사용)
CREATE TABLE game_member (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id        BIGINT  NOT NULL REFERENCES game (id) ON DELETE CASCADE,
    member_id      BIGINT  NOT NULL REFERENCES member (id),
    display_order  INT     NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (game_id, member_id)
);
