-- 홈 위젯 스키마 (05-api-spec.md §1.3, T-40): 멘토 캐러셀 + Q&A + 모집 링크.
-- 번호는 착수 직전 db/migration 확인 후 V16으로 확정했다 — 게임 스키마(별도 브랜치,
-- T-36)가 이미 V15를 쓰고 있어 충돌을 피했다(ADR-001).

CREATE TABLE mentor_slot (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      BIGINT NOT NULL REFERENCES member (id),
    display_order  INT    NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (member_id)
);

CREATE TABLE qna_item (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question       VARCHAR(200) NOT NULL,
    answer         TEXT         NOT NULL,
    display_order  INT          NOT NULL,
    is_published   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_qna_order ON qna_item (display_order);

-- INV-22: 항상 1행. 고정 id=1 upsert 방식을 쓴다(부분 유니크 인덱스보다 단순).
CREATE TABLE recruit_link (
    id                BIGINT PRIMARY KEY,
    google_form_url   VARCHAR(300) NOT NULL,
    is_open           BOOLEAN      NOT NULL DEFAULT FALSE,
    close_date        DATE,
    closed_message    VARCHAR(100) NOT NULL DEFAULT '모집 예정',
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_recruit_link_single_row CHECK (id = 1)
);

CREATE TABLE recruit_link_history (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    google_form_url VARCHAR(300) NOT NULL,
    is_open         BOOLEAN      NOT NULL,
    changed_by      BIGINT       REFERENCES member (id),
    changed_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_recruit_link_history ON recruit_link_history (changed_at DESC);
