CREATE TABLE reservation_group (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id        BIGINT       NOT NULL REFERENCES member (id),
    frequency        VARCHAR(20)  NOT NULL,
    weekdays         VARCHAR(40)  NOT NULL,
    start_minute     SMALLINT     NOT NULL,
    end_minute       SMALLINT     NOT NULL,
    repeat_end_date  DATE         NOT NULL,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_reservation_group_frequency CHECK (frequency IN ('WEEKLY', 'BIWEEKLY')),
    CONSTRAINT ck_reservation_group_minute_range
        CHECK (start_minute >= 0 AND end_minute <= 1440 AND start_minute < end_minute),
    CONSTRAINT ck_reservation_group_minute_aligned
        CHECK (start_minute % 30 = 0 AND end_minute % 30 = 0)
);

CREATE INDEX idx_reservation_group_member_id ON reservation_group (member_id);

CREATE TABLE reservation (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id             BIGINT       NOT NULL REFERENCES member (id),
    reservation_group_id  BIGINT       REFERENCES reservation_group (id),
    reservation_date      DATE         NOT NULL,
    start_minute          SMALLINT     NOT NULL,
    end_minute            SMALLINT     NOT NULL,
    purpose               VARCHAR(200) NOT NULL,
    headcount             SMALLINT     NOT NULL,
    cancelled_at          TIMESTAMPTZ,
    created_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_reservation_minute_range
        CHECK (start_minute >= 0 AND end_minute <= 1440 AND start_minute < end_minute),
    CONSTRAINT ck_reservation_minute_aligned
        CHECK (start_minute % 30 = 0 AND end_minute % 30 = 0),
    CONSTRAINT ck_reservation_headcount_positive CHECK (headcount > 0)
);

CREATE INDEX idx_reservation_member_id_date ON reservation (member_id, reservation_date);
CREATE INDEX idx_reservation_date ON reservation (reservation_date);
CREATE INDEX idx_reservation_group_id ON reservation (reservation_group_id);

-- 방이 하나뿐이라 member_id 조건 없이, 취소되지 않은 예약끼리만 겹치면 막는다.
-- tsrange 기본 range 타입만 사용하므로 btree_gist 확장 불필요.
ALTER TABLE reservation
    ADD CONSTRAINT ck_reservation_no_overlap
    EXCLUDE USING gist (
        tsrange(
            (reservation_date::timestamp + make_interval(mins => start_minute::int)),
            (reservation_date::timestamp + make_interval(mins => end_minute::int)),
            '[)'
        ) WITH &&
    )
    WHERE (cancelled_at IS NULL);
