CREATE TABLE member (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_number       VARCHAR(10)  NOT NULL,
    password             VARCHAR(72)  NOT NULL,
    name                 VARCHAR(50)  NOT NULL,
    track                VARCHAR(20)  NOT NULL,
    generation           VARCHAR(20)  NOT NULL,
    member_type          VARCHAR(20)  NOT NULL,
    university           VARCHAR(100) NOT NULL,
    email                VARCHAR(255) NOT NULL,
    phone_number         VARCHAR(20),
    github_id            VARCHAR(39),
    status               VARCHAR(20)  NOT NULL DEFAULT 'PENDING_SETUP',
    role                 VARCHAR(20)  NOT NULL DEFAULT 'MEMBER',
    login_fail_count     SMALLINT     NOT NULL DEFAULT 0,
    locked_until         TIMESTAMPTZ,
    password_changed_at  TIMESTAMPTZ,
    last_login_at        TIMESTAMPTZ,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_member_student_number UNIQUE (student_number),
    CONSTRAINT uk_member_email UNIQUE (email),
    CONSTRAINT ck_member_student_number_format CHECK (student_number ~ '^[0-9]{8,10}$'),
    CONSTRAINT ck_member_track CHECK (track IN
        ('FRONTEND', 'BACKEND', 'ANDROID', 'IOS', 'PM', 'DATA', 'DESIGN', 'DEVOPS', 'PS', 'GAME')),
    CONSTRAINT ck_member_type CHECK (member_type IN ('MENTOR', 'REGULAR', 'BEGINNER')),
    CONSTRAINT ck_member_status CHECK (status IN ('PENDING_SETUP', 'ACTIVE', 'LOCKED', 'WITHDRAWN')),
    CONSTRAINT ck_member_role CHECK (role IN ('MEMBER', 'ADMIN'))
);

CREATE INDEX idx_member_status ON member (status);
