CREATE TABLE position (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(30)  NOT NULL,
    name        VARCHAR(50)  NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_position_code UNIQUE (code)
);

INSERT INTO position (code, name) VALUES
    ('PRESIDENT', '회장'),
    ('VICE_PRESIDENT', '부회장'),
    ('FRONTEND_LEAD', 'FrontEnd 트랙장'),
    ('BACKEND_LEAD', 'BackEnd 트랙장'),
    ('ANDROID_LEAD', 'Android 트랙장'),
    ('IOS_LEAD', 'iOS 트랙장'),
    ('PM_LEAD', 'PM 트랙장'),
    ('DATA_LEAD', 'DA 트랙장'),
    ('DESIGN_LEAD', 'Design 트랙장'),
    ('GAME_LEAD', 'Game 트랙장'),
    ('SECURITY_LEAD', 'Security 트랙장'),
    ('FRONTEND_EDUCATION_LEAD', 'FrontEnd 교육장'),
    ('BACKEND_EDUCATION_LEAD', 'BackEnd 교육장'),
    ('ANDROID_EDUCATION_LEAD', 'Android 교육장'),
    ('IOS_EDUCATION_LEAD', 'iOS 교육장'),
    ('PM_EDUCATION_LEAD', 'PM 교육장'),
    ('DATA_EDUCATION_LEAD', 'DA 교육장'),
    ('DESIGN_EDUCATION_LEAD', 'Design 교육장'),
    ('GAME_EDUCATION_LEAD', 'Game 교육장'),
    ('SECURITY_EDUCATION_LEAD', 'Security 교육장');

CREATE TABLE member_position (
    member_id   BIGINT NOT NULL REFERENCES member (id),
    position_id BIGINT NOT NULL REFERENCES position (id),

    CONSTRAINT pk_member_position PRIMARY KEY (member_id, position_id)
);

INSERT INTO member_position (member_id, position_id)
SELECT m.id, p.id
FROM member m
JOIN position p ON p.name = m.position
WHERE m.position IS NOT NULL AND m.position <> '';
