-- 회비 학기. 월 회비를 학기마다 저장한다. 같은 학기 동시 생성은 유니크 제약으로 막는다.
CREATE TABLE dues_semester (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    year            SMALLINT     NOT NULL,
    term            SMALLINT     NOT NULL,
    monthly_amount  BIGINT       NOT NULL,
    created_by      BIGINT       REFERENCES member (id),
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_dues_semester_year_term UNIQUE (year, term),
    CONSTRAINT ck_dues_semester_term CHECK (term IN (1, 2)),
    CONSTRAINT ck_dues_semester_year CHECK (year BETWEEN 2000 AND 2100),
    CONSTRAINT ck_dues_semester_monthly_amount CHECK (monthly_amount > 0)
);

-- 학기 명단. 생성 때 스냅샷하고, 관리자 API로 추가·정정한다(삭제 없음, 마감 없음).
-- applicable=false면 이 학기 납부 비대상(전 월 NOT_APPLICABLE)이다. 비대상 회원에게는 회비 연결이 없다(서비스가 보장).
CREATE TABLE dues_semester_member (
    semester_id  BIGINT       NOT NULL REFERENCES dues_semester (id),
    member_id    BIGINT       NOT NULL REFERENCES member (id),
    applicable   BOOLEAN      NOT NULL,
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),

    PRIMARY KEY (semester_id, member_id)
);

CREATE INDEX idx_dues_semester_member_member_id ON dues_semester_member (member_id);
