-- 장부 내역. 은행 거래내역 가져오기(PR5)로만 생기고, 분류·상대·내용·비고만 고칠 수 있다.
CREATE TABLE ledger_entry (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at       TIMESTAMP    NOT NULL,           -- KST 벽시계 시각(은행 원본, 초 단위)
    occurred_seq      SMALLINT     NOT NULL DEFAULT 0, -- 같은 occurred_at 안에서 은행 잔액이 이어지는 순서
    type              VARCHAR(20)  NOT NULL,
    category          VARCHAR(20)  NOT NULL,
    counterparty      VARCHAR(100) NOT NULL,
    description       VARCHAR(200) NOT NULL,
    note              VARCHAR(500) NOT NULL DEFAULT '',
    amount            BIGINT       NOT NULL,
    bank_balance      BIGINT       NOT NULL,           -- 은행 파일의 거래 후 잔액 = 응답 balance
    source_file_name  VARCHAR(255),
    row_key           CHAR(64),                        -- 은행 거래 지문(SHA-256 hex)
    created_by        BIGINT       REFERENCES member (id),
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT ck_ledger_entry_type CHECK (type IN ('DEPOSIT', 'WITHDRAWAL')),
    CONSTRAINT ck_ledger_entry_category CHECK (category IN ('DUES', 'EVENT', 'OPERATION', 'ETC')),
    CONSTRAINT ck_ledger_entry_amount_positive CHECK (amount > 0)
);

CREATE UNIQUE INDEX uq_ledger_entry_row_key ON ledger_entry (row_key) WHERE row_key IS NOT NULL;
CREATE INDEX idx_ledger_entry_order ON ledger_entry (occurred_at, occurred_seq, id);

-- 장부 기록 ↔ (회원, 학기). 기록 하나에 연결 하나. 스냅샷은 두지 않는다.
-- 납부 비대상 회원에게는 연결이 없다(서비스가 명단 행 잠금으로 보장).
CREATE TABLE dues_link (
    entry_id     BIGINT       PRIMARY KEY REFERENCES ledger_entry (id),
    semester_id  BIGINT       NOT NULL,
    member_id    BIGINT       NOT NULL,
    linked_by    BIGINT       REFERENCES member (id),
    linked_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT fk_dues_link_semester_member FOREIGN KEY (semester_id, member_id)
        REFERENCES dues_semester_member (semester_id, member_id)
);

CREATE INDEX idx_dues_link_semester_member ON dues_link (semester_id, member_id);
