CREATE TABLE refresh_token (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id        BIGINT       NOT NULL REFERENCES member (id),
    token_hash       VARCHAR(64)  NOT NULL,
    expires_at       TIMESTAMPTZ  NOT NULL,
    remember_me      BOOLEAN      NOT NULL DEFAULT FALSE,
    revoked_at       TIMESTAMPTZ,
    rotated_from_id  BIGINT REFERENCES refresh_token (id),
    user_agent       VARCHAR(255),
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_refresh_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_refresh_token_member_id ON refresh_token (member_id);
CREATE INDEX idx_refresh_token_expires_at ON refresh_token (expires_at);
