CREATE TABLE password_reset_token (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id      BIGINT       NOT NULL REFERENCES member (id),
    token_hash     VARCHAR(64)  NOT NULL,
    expires_at     TIMESTAMPTZ  NOT NULL,
    used_at        TIMESTAMPTZ,
    requested_ip   VARCHAR(45),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash)
);

CREATE INDEX idx_password_reset_token_member_id ON password_reset_token (member_id, created_at DESC);
