CREATE TABLE track (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(20)  NOT NULL,
    name        VARCHAR(50)  NOT NULL,
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_track_code UNIQUE (code)
);

-- member.track(VARCHAR enum)의 10개 값 + 홈페이지에는 있으나 인터널 enum에는 없던 SECURITY.
INSERT INTO track (code, name) VALUES
    ('FRONTEND', '프론트엔드'),
    ('BACKEND', '백엔드'),
    ('ANDROID', '안드로이드'),
    ('IOS', 'iOS'),
    ('PM', '기획'),
    ('DATA', '데이터'),
    ('DESIGN', '디자인'),
    ('DEVOPS', '데브옵스'),
    ('PS', 'PS'),
    ('GAME', '게임'),
    ('SECURITY', '보안');
