ALTER TABLE member ADD COLUMN position VARCHAR(50);
ALTER TABLE member ADD COLUMN birth_date DATE;
ALTER TABLE member ADD COLUMN dues_required BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE member ADD COLUMN photo_url VARCHAR(500);
