-- 홈페이지 CMS 스키마 (05-api-spec.md §1.2). track_page는 트랙 마스터(V7)를 참조한다.
-- 최상위 엔티티(track_page/curriculum/activity_category/activity)만 soft delete를 쓰고,
-- 하위 트리는 ON DELETE CASCADE로 물리 삭제한다.

-- ===== 홈페이지 노출 프로필 (track 1 : track_page 0..1) =====
CREATE TABLE track_page (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_id         BIGINT       NOT NULL REFERENCES track (id),
    slug             VARCHAR(50)  NOT NULL,
    display_name     VARCHAR(50)  NOT NULL,
    tagline          VARCHAR(120) NOT NULL,
    hero_image_url   VARCHAR(500),
    og_image_url     VARCHAR(500),
    seo_description  VARCHAR(200),
    display_order    INT          NOT NULL,
    is_published     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at       TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_track_page_slug ON track_page (slug) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX uq_track_page_track ON track_page (track_id) WHERE deleted_at IS NULL;

CREATE TABLE track_study_point (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_page_id   BIGINT       NOT NULL REFERENCES track_page (id) ON DELETE CASCADE,
    title           VARCHAR(60)  NOT NULL,
    description     VARCHAR(200) NOT NULL,
    icon_image_url  VARCHAR(500),
    display_order   INT          NOT NULL,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_study_point_page ON track_study_point (track_page_id, display_order);

CREATE TABLE tech_stack (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL,
    icon_url    VARCHAR(500) NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_tech_stack_name UNIQUE (name)
);

CREATE TABLE track_page_tech_stack (
    track_page_id  BIGINT NOT NULL REFERENCES track_page (id) ON DELETE CASCADE,
    tech_stack_id  BIGINT NOT NULL REFERENCES tech_stack (id) ON DELETE CASCADE,
    display_order  INT    NOT NULL,

    PRIMARY KEY (track_page_id, tech_stack_id)
);

-- 명부(member)가 이미 구현되어 있으므로 FK를 즉시 적용한다 (ADR-012).
CREATE TABLE track_page_member (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_page_id  BIGINT  NOT NULL REFERENCES track_page (id) ON DELETE CASCADE,
    member_id      BIGINT  NOT NULL REFERENCES member (id),
    display_order  INT     NOT NULL,
    is_visible     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT uk_track_page_member UNIQUE (track_page_id, member_id)
);

-- ===== 커리큘럼 =====
CREATE TABLE curriculum (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    track_page_id  BIGINT      NOT NULL REFERENCES track_page (id) ON DELETE CASCADE,
    name           VARCHAR(50) NOT NULL,
    is_published   BOOLEAN     NOT NULL DEFAULT FALSE,
    display_order  INT         NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ
);
-- INV-2: 트랙당 공개 세트는 1개만 (ADR-004)
CREATE UNIQUE INDEX uq_curriculum_published
    ON curriculum (track_page_id) WHERE is_published AND deleted_at IS NULL;

CREATE TABLE curriculum_week (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    curriculum_id  BIGINT NOT NULL REFERENCES curriculum (id) ON DELETE CASCADE,
    week_from      INT    NOT NULL,
    week_to        INT,
    display_order  INT    NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT ck_week_range CHECK (week_to IS NULL OR week_to >= week_from),
    CONSTRAINT ck_week_from CHECK (week_from BETWEEN 1 AND 99)
);
CREATE INDEX idx_week_curriculum ON curriculum_week (curriculum_id, display_order);

CREATE TABLE curriculum_topic (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_id        BIGINT       NOT NULL REFERENCES curriculum_week (id) ON DELETE CASCADE,
    title          VARCHAR(200) NOT NULL,
    display_order  INT          NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_topic_week ON curriculum_topic (week_id, display_order);

CREATE TABLE curriculum_topic_detail (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id       BIGINT       NOT NULL REFERENCES curriculum_topic (id) ON DELETE CASCADE,
    content        VARCHAR(300) NOT NULL,
    display_order  INT          NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_detail_topic ON curriculum_topic_detail (topic_id, display_order);

-- ===== 활동 =====
CREATE TABLE activity_category (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            VARCHAR(30) NOT NULL,
    name            VARCHAR(30) NOT NULL,
    headline        VARCHAR(200),
    hero_image_url  VARCHAR(500),
    display_order   INT         NOT NULL,
    is_published    BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at      TIMESTAMPTZ
);
CREATE UNIQUE INDEX uq_activity_category_slug ON activity_category (slug) WHERE deleted_at IS NULL;

CREATE TABLE activity (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id    BIGINT       NOT NULL REFERENCES activity_category (id),
    year           INT          NOT NULL,
    month          INT          NOT NULL,
    title          VARCHAR(80)  NOT NULL,
    summary        VARCHAR(200) NOT NULL,
    content        TEXT,
    external_url   VARCHAR(500),
    display_order  INT          NOT NULL,
    is_published   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    deleted_at     TIMESTAMPTZ,

    CONSTRAINT ck_activity_month CHECK (month BETWEEN 1 AND 12),
    CONSTRAINT ck_activity_year CHECK (year BETWEEN 2000 AND 2100)
);
CREATE INDEX idx_activity_timeline
    ON activity (category_id, year DESC, month DESC, display_order)
    WHERE deleted_at IS NULL;

CREATE TABLE activity_image (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_id    BIGINT       NOT NULL REFERENCES activity (id) ON DELETE CASCADE,
    image_url      VARCHAR(500) NOT NULL,
    display_order  INT          NOT NULL,
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_activity_image ON activity_image (activity_id, display_order);

-- ===== 미디어 라이브러리 (콘텐츠 테이블과 FK로 묶지 않는다 · ADR-009) =====
CREATE TABLE image_asset (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    s3_key         VARCHAR(300) NOT NULL,
    url            VARCHAR(500) NOT NULL,
    original_name  VARCHAR(255) NOT NULL,
    content_type   VARCHAR(100) NOT NULL,
    byte_size      BIGINT       NOT NULL,
    purpose        VARCHAR(30)  NOT NULL,
    is_confirmed   BOOLEAN      NOT NULL DEFAULT FALSE,
    uploaded_by    BIGINT       REFERENCES member (id),
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),

    CONSTRAINT uk_image_asset_s3_key UNIQUE (s3_key)
);
CREATE INDEX idx_image_asset_library ON image_asset (purpose, created_at DESC) WHERE is_confirmed;
